package com.chaitu.twitter.repository;

import java.io.UnsupportedEncodingException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/twitter")
public class TweetController 
{
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	public TweetDAO tweetRepository;
	
	@Autowired
	public TwitterMain twitterMain;

	@GetMapping(path="/load")
	public @ResponseBody String loadAllTweets() throws UnsupportedEncodingException 
	{
		// This returns a JSON or XML with the users
		twitterMain.loadIntoDB(tweetRepository);
		return "Success";
	}

}
